/**
 * Signal Schema
 *
 * Defines the structure of behavioral signals generated by the engine.
 * Signals are abstract, context-agnostic, and reusable across features.
 */

/**
 * Signal categories - high-level groupings
 */
export type SignalCategory =
  | 'work_style' // How someone approaches work
  | 'collaboration' // How someone works with others
  | 'decision_making' // How someone makes decisions
  | 'motivation' // What drives someone
  | 'environment' // Preferred work environment
  | 'growth'; // Learning and development style

/**
 * Individual signal identifiers
 * These are the atomic units of personality insight
 */
export type SignalId =
  // Work Style signals
  | 'structure_preference' // Structured vs. flexible approach
  | 'pace_preference' // Fast-paced vs. steady approach
  | 'detail_orientation' // Big picture vs. detail focused
  | 'task_approach' // Sequential vs. parallel task handling

  // Collaboration signals
  | 'collaboration_style' // Independent vs. team-oriented
  | 'communication_style' // Direct vs. diplomatic
  | 'conflict_approach' // Confrontational vs. harmonizing
  | 'leadership_tendency' // Leading vs. supporting

  // Decision Making signals
  | 'decision_style' // Analytical vs. intuitive
  | 'risk_tolerance' // Risk-seeking vs. risk-averse
  | 'change_adaptability' // Change-embracing vs. stability-seeking

  // Motivation signals
  | 'achievement_drive' // Results vs. process oriented
  | 'recognition_need' // Public vs. private recognition preference
  | 'autonomy_need' // Independence vs. guidance preference

  // Environment signals
  | 'social_energy' // Energized by people vs. solitude
  | 'noise_tolerance' // Thrives in busy vs. quiet environments
  | 'routine_preference'; // Routine vs. variety seeking

/**
 * A single behavioral signal
 */
export interface Signal {
  /** Unique identifier for this signal type */
  id: SignalId;

  /** Category this signal belongs to */
  category: SignalCategory;

  /**
   * Signal value on a normalized scale
   * -1.0 = strong tendency toward one pole
   *  0.0 = balanced/neutral
   * +1.0 = strong tendency toward opposite pole
   *
   * The interpretation of poles depends on the signal.
   * See SignalId documentation for pole meanings.
   */
  value: number;

  /**
   * Confidence in this signal (0.0 to 1.0)
   * Based on:
   * - Number of relevant questions answered
   * - Consistency of answers
   * - Response time patterns
   */
  confidence: number;

  /**
   * Which test(s) contributed to this signal
   */
  sources: string[];
}

/**
 * Signal metadata for documentation/UI purposes
 * NOT used in engine logic - only for consumers
 */
export interface SignalMetadata {
  id: SignalId;
  category: SignalCategory;
  /** Human-readable name (English) */
  name: string;
  /** Description of what this signal measures */
  description: string;
  /** Description of the -1.0 pole */
  negativePole: string;
  /** Description of the +1.0 pole */
  positivePole: string;
}

/**
 * Complete signal metadata catalog
 * Used by adapters to generate human-readable descriptions
 */
export const SIGNAL_METADATA: Record<SignalId, SignalMetadata> = {
  // Work Style
  structure_preference: {
    id: 'structure_preference',
    category: 'work_style',
    name: 'Structure Preference',
    description: 'Preference for structured vs. flexible work approaches',
    negativePole: 'Prefers flexibility and adaptability',
    positivePole: 'Prefers clear structure and processes',
  },
  pace_preference: {
    id: 'pace_preference',
    category: 'work_style',
    name: 'Work Pace',
    description: 'Preferred speed and urgency in work',
    negativePole: 'Prefers steady, measured pace',
    positivePole: 'Thrives in fast-paced environments',
  },
  detail_orientation: {
    id: 'detail_orientation',
    category: 'work_style',
    name: 'Detail Orientation',
    description: 'Focus on details vs. big picture thinking',
    negativePole: 'Big picture, strategic thinker',
    positivePole: 'Detail-oriented, thorough',
  },
  task_approach: {
    id: 'task_approach',
    category: 'work_style',
    name: 'Task Approach',
    description: 'How tasks are organized and executed',
    negativePole: 'Handles multiple tasks simultaneously',
    positivePole: 'Focuses on one task at a time',
  },

  // Collaboration
  collaboration_style: {
    id: 'collaboration_style',
    category: 'collaboration',
    name: 'Collaboration Style',
    description: 'Preference for working independently vs. with others',
    negativePole: 'Works best independently',
    positivePole: 'Thrives in team settings',
  },
  communication_style: {
    id: 'communication_style',
    category: 'collaboration',
    name: 'Communication Style',
    description: 'Direct vs. diplomatic communication approach',
    negativePole: 'Diplomatic, tactful communicator',
    positivePole: 'Direct, straightforward communicator',
  },
  conflict_approach: {
    id: 'conflict_approach',
    category: 'collaboration',
    name: 'Conflict Approach',
    description: 'How conflict and disagreement are handled',
    negativePole: 'Seeks harmony, avoids conflict',
    positivePole: 'Addresses conflict directly',
  },
  leadership_tendency: {
    id: 'leadership_tendency',
    category: 'collaboration',
    name: 'Leadership Tendency',
    description: 'Natural inclination to lead vs. support',
    negativePole: 'Prefers supporting role',
    positivePole: 'Natural leader, takes charge',
  },

  // Decision Making
  decision_style: {
    id: 'decision_style',
    category: 'decision_making',
    name: 'Decision Style',
    description: 'Analytical vs. intuitive decision making',
    negativePole: 'Relies on intuition and experience',
    positivePole: 'Data-driven, analytical approach',
  },
  risk_tolerance: {
    id: 'risk_tolerance',
    category: 'decision_making',
    name: 'Risk Tolerance',
    description: 'Comfort with uncertainty and risk',
    negativePole: 'Risk-averse, cautious',
    positivePole: 'Comfortable with risk, bold',
  },
  change_adaptability: {
    id: 'change_adaptability',
    category: 'decision_making',
    name: 'Change Adaptability',
    description: 'Response to change and new situations',
    negativePole: 'Values stability and consistency',
    positivePole: 'Embraces change, adaptable',
  },

  // Motivation
  achievement_drive: {
    id: 'achievement_drive',
    category: 'motivation',
    name: 'Achievement Drive',
    description: 'Focus on results vs. process',
    negativePole: 'Process-oriented, enjoys the journey',
    positivePole: 'Results-driven, goal-focused',
  },
  recognition_need: {
    id: 'recognition_need',
    category: 'motivation',
    name: 'Recognition Need',
    description: 'Desire for public vs. private acknowledgment',
    negativePole: 'Prefers private acknowledgment',
    positivePole: 'Motivated by public recognition',
  },
  autonomy_need: {
    id: 'autonomy_need',
    category: 'motivation',
    name: 'Autonomy Need',
    description: 'Preference for independence vs. guidance',
    negativePole: 'Appreciates guidance and direction',
    positivePole: 'Values independence and autonomy',
  },

  // Environment
  social_energy: {
    id: 'social_energy',
    category: 'environment',
    name: 'Social Energy',
    description: 'Energy from social interaction vs. solitude',
    negativePole: 'Recharges through solitude',
    positivePole: 'Energized by social interaction',
  },
  noise_tolerance: {
    id: 'noise_tolerance',
    category: 'environment',
    name: 'Noise Tolerance',
    description: 'Preference for busy vs. quiet work environments',
    negativePole: 'Prefers quiet, calm environments',
    positivePole: 'Thrives in busy, dynamic environments',
  },
  routine_preference: {
    id: 'routine_preference',
    category: 'environment',
    name: 'Routine Preference',
    description: 'Preference for routine vs. variety',
    negativePole: 'Seeks variety and new experiences',
    positivePole: 'Values routine and predictability',
  },
};
