-- Add personality signals to profiles
-- Stores behavioral signals generated by Personality Engine

-- Add columns to store personality signals
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS personality_signals JSONB;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS personality_analyzed_at TIMESTAMPTZ;

-- Skills array for job matching
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}';

-- Add is_primary column if not exists
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT FALSE;

-- Create index for profiles with personality data
CREATE INDEX IF NOT EXISTS idx_profiles_has_personality ON profiles((personality_signals IS NOT NULL));

-- Create index for primary profiles
CREATE INDEX IF NOT EXISTS idx_profiles_primary ON profiles(user_id, is_primary) WHERE is_primary = TRUE;

-- Comment on columns
COMMENT ON COLUMN profiles.personality_signals IS 'Behavioral signals generated by Personality Engine (JSON array of Signal objects)';
COMMENT ON COLUMN profiles.personality_analyzed_at IS 'When personality test was last completed';
COMMENT ON COLUMN profiles.skills IS 'Array of skill names for job matching';
COMMENT ON COLUMN profiles.is_primary IS 'Whether this is the users primary profile';
